In [62]:
import os
import json
import pandas as pd

In [63]:
path = "C:/Phonepay_Transaction_insights/pulse/data/aggregated/transaction/country/india/state/"

In [64]:
aggregated_state = os.listdir(path)
column = {"States":[],"Year":[],"Quarter":[],"Transaction_Name":[],"Transaction_Count":[],"Transaction_Amount":[],"Transaction_Type":[]}

In [75]:
for state in aggregated_state:
    cur_state = os.path.join(path,state)
    current_state = os.listdir(cur_state)
    for year in current_state:
        sta_year = os.path.join(cur_state,year)
        state_year = os.listdir(sta_year)
        for file in state_year:
            file_path = os.path.join(sta_year,file)
            if file.endswith(".json"):
                with open (file_path,"r") as f:
                    data = json.load(f)
                    for i in data["data"]["transactionData"]:
                        name = i["name"]
                        count = i["paymentInstruments"][0]["count"]
                        typ = i["paymentInstruments"][0]["type"]
                        amount =i["paymentInstruments"][0]["amount"]
                        column["Transaction_Name"].append(name)
                        column["Transaction_Count"].append(count)
                        column["Transaction_Type"].append(typ)
                        column["Transaction_Amount"].append(amount)
                        column["States"].append(state)
                        column["Year"].append(year)
                        quarter = int(os.path.splitext(file)[0])
                        column["Quarter"].append(quarter)
aggregated_transaction = pd.DataFrame(column)

aggregated_transaction['States'] = aggregated_transaction['States'].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar Islands')
aggregated_transaction['States'] = aggregated_transaction['States'].str.replace('-',' ')
aggregated_transaction['States'] = aggregated_transaction['States'].str.title()
aggregated_transaction['States'] = aggregated_transaction['States'].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

0        False
1        False
2        False
3        False
4        False
         ...
15097     True
15098     True
15099     True
15100     True
15101     True
Length: 15102, dtype: bool

In [74]:
aggregated_transaction

,States,Year,Quarter,Transaction_Name,Transaction_Count,Transaction_Amount,Transaction_Type
0,Andaman & Nicobar Islands,2018,1,Recharge & bill payments,4200,1.845307e+06,TOTAL
1,Andaman & Nicobar Islands,2018,1,Peer-to-peer payments,1871,1.213866e+07,TOTAL
2,Andaman & Nicobar Islands,2018,1,Merchant payments,298,4.525072e+05,TOTAL
3,Andaman & Nicobar Islands,2018,1,Financial Services,33,1.060142e+04,TOTAL
4,Andaman & Nicobar Islands,2018,1,Others,256,1.846899e+05,TOTAL
...,...,...,...,...,...,...,...
10063,West Bengal,2024,4,Merchant payments,655100809,3.892862e+11,TOTAL
10064,West Bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12,TOTAL
10065,West Bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10,TOTAL
10066,West Bengal,2024,4,Financial Services,2352084,8.472965e+08,TOTAL
10067,West Bengal,2024,4,Others,421806,5.053641e+08,TOTAL

In [25]:
path1 = "C:/Phonepay_Transaction_insights/pulse/data/aggregated/user/country/india/state/"

In [26]:
aggregated_state = os.listdir(path1)
column1= {"States":[],"Year":[],"Quarter":[],"brand":[],"count":[],"percentage":[]}

In [27]:
for state in aggregated_state:
    cur_state = os.path.join(path1,state)
    current_state = os.listdir(cur_state)
    for year in current_state:
        sta_year = os.path.join(cur_state,year)
        state_year = os.listdir(sta_year)
        for file in state_year:
            file_path = os.path.join(sta_year,file)
            if file.endswith(".json"):
                with open (file_path,"r") as f:
                    data1 = json.load(f)
                    try:
                        for i in data1["data"]['usersByDevice']:
                            brand = i["brand"]
                            count = i["count"]
                            percentage = i["percentage"]
                            column1["brand"].append(brand)
                            column1["count"].append(count)
                            column1["percentage"].append(percentage)
                            column1["States"].append(state)
                            column1["Year"].append(year)
                            quarter = int(os.path.splitext(file)[0])
                            column1["Quarter"].append(quarter)
                    except:
                        pass
aggregated_user = pd.DataFrame(column1)

In [30]:
path2 = "C:/Phonepay_Transaction_insights/pulse/data/map/transaction/hover/country/india/state/"

In [31]:
aggregated_map = os.listdir(path2)
column2= {"States":[],"Year":[],"Quarter":[],"District_Name":[],"Transaction_Count":[],"Transaction_Amount":[],"Transaction_Type":[]}

In [32]:
for state in aggregated_map:
    cur_state = os.path.join(path2,state)
    current_state = os.listdir(cur_state)
    for year in current_state:
        sta_year = os.path.join(cur_state,year)
        state_year = os.listdir(sta_year)
        for file in state_year:
            file_path = os.path.join(sta_year,file)
            if file.endswith(".json"):
                with open (file_path,"r") as f:
                    data2 = json.load(f)
                    for i in data2["data"]["hoverDataList"]:
                        name = i["name"]
                        typ = i["metric"][0]["type"]
                        count = i["metric"][0]["count"]
                        amount =i["metric"][0]["amount"]
                        column2["District_Name"].append(name)
                        column2["Transaction_Count"].append(count)
                        column2["Transaction_Type"].append(typ)
                        column2["Transaction_Amount"].append(amount)
                        column2["States"].append(state)
                        column2["Year"].append(year)
                        quarter = int(os.path.splitext(file)[0])
                        column2["Quarter"].append(quarter)

aggre_map = pd.DataFrame(column2)

In [34]:
path3 = "C:/Phonepay_Transaction_insights/pulse/data/map/user/hover/country/india/state/"

In [35]:
aggregated_use = os.listdir(path3)
column3= {"States":[],"Year":[],"Quarter":[],"District_Name":[],"Registered_users":[],"AppOpens":[]}

In [36]:
for state in aggregated_use:
    cur_state = os.path.join(path3,state)
    current_state = os.listdir(cur_state)
    for year in current_state:
        sta_year = os.path.join(cur_state,year)
        state_year = os.listdir(sta_year)
        for file in state_year:
            file_path = os.path.join(sta_year,file)
            if file.endswith(".json"):
                with open (file_path,"r") as f:
                    data3 = json.load(f)
                    for i in data3["data"]["hoverData"].items():
                      
                      name = i[0]
                      reg_users = i[1]["registeredUsers"]
                      count = i[1]["appOpens"]
                    column3["District_Name"].append(name)
                    column3["Registered_users"].append(reg_users)
                    column3["AppOpens"].append(count)
                    
                    column3["States"].append(state)
                    column3["Year"].append(year)
                    quarter = int(os.path.splitext(file)[0])
                    column3["Quarter"].append(quarter)
                    
Map_users = pd.DataFrame(column3)

In [38]:
path4 = "C:/Phonepay_Transaction_insights/pulse/data/aggregated/insurance/country/india/state/"

In [39]:
aggregated_state = os.listdir(path4)
column4 = {"States":[],"Year":[],"Quarter":[],"Transaction_Name":[],"Transaction_Count":[],"Transaction_Amount":[],"Transaction_Type":[]}

In [41]:
for state in aggregated_state:
    cur_state = os.path.join(path4,state)
    current_state = os.listdir(cur_state)
    for year in current_state:
        sta_year = os.path.join(cur_state,year)
        state_year = os.listdir(sta_year)
        for file in state_year:
            file_path = os.path.join(sta_year,file)
            if file.endswith(".json"):
                with open (file_path,"r") as f:
                    data4 = json.load(f)
                    for i in data4["data"]["transactionData"]:
                        name = i["name"]
                        count = i["paymentInstruments"][0]["count"]
                        typ = i["paymentInstruments"][0]["type"]
                        amount =i["paymentInstruments"][0]["amount"]
                        column4["Transaction_Name"].append(name)
                        column4["Transaction_Count"].append(count)
                        column4["Transaction_Type"].append(typ)
                        column4["Transaction_Amount"].append(amount)
                        column4["States"].append(state)
                        column4["Year"].append(year)
                        quarter = int(os.path.splitext(file)[0])
                        column4["Quarter"].append(quarter)
aggregated_insurance = pd.DataFrame(column4)

In [77]:
path5 = "C:/Phonepay_Transaction_insights/pulse/data/map/insurance/hover/country/india/state/"

In [78]:
aggregated_map = os.listdir(path5)
column5= {"States":[],"Year":[],"Quarter":[],"District_Name":[],"Transaction_Count":[],"Transaction_Amount":[],"Transaction_Type":[]}

In [79]:
for state in aggregated_state:
    cur_state = os.path.join(path5,state)
    current_state = os.listdir(cur_state)
    for year in current_state:
        sta_year = os.path.join(cur_state,year)
        state_year = os.listdir(sta_year)
        for file in state_year:
            file_path = os.path.join(sta_year,file)
            if file.endswith(".json"):
                with open (file_path,"r") as f:
                    data5 = json.load(f)
                    for i in data5["data"]['hoverDataList']:
                        name = i["name"]
                        type = i["metric"][0]["type"]
                        count = i["metric"][0]["count"]
                        amount = i["metric"][0]["amount"]
                        column5["States"].append(state)
                        column5["Year"].append(year)
                        quarter = int(os.path.splitext(file)[0])
                        column5["Quarter"].append(quarter)
                        column5["District_Name"].append(name)
                        column5["Transaction_Count"].append(count)
                        column5["Transaction_Type"].append(type)
                        column5["Transaction_Amount"].append(amount)
                        
map_insurance = pd.DataFrame(column5)

In [21]:
path6 = "C:/Phonepay_Transaction_insights/pulse/data/top/insurance/country/india/state/"

In [22]:
aggregated_map = os.listdir(path6)
column6= {"States":[],"Year":[],"Quarter":[],"Pin_code":[],"Transaction_Amount":[],"Transaction_Type":[],"Transaction_count":[]}

In [23]:
for state in aggregated_map:
    curr_state = os.path.join(path6,state)
    current_state = os.listdir(curr_state)
    for year in current_state:
        curr_year = os.path.join(curr_state,year)
        current_year = os.listdir(curr_year)
        for file in current_year:
            file_path = os.path.join(curr_year,file)
            if file.endswith(".json"):
                with open(file_path,"r") as f:
                    data6 = json.load(f)
                    for i in data6['data']['pincodes']:
                        pin_code = i['entityName']
                        type = i['metric']["type"]
                        count = i['metric']["count"]
                        amount = i['metric']["amount"]
                        column6["States"].append(state)
                        column6["Year"].append(year)
                        quarter = int(os.path.splitext(file)[0])
                        column6["Quarter"].append(quarter)
                        column6["Pin_code"].append(pin_code)
                        column6["Transaction_count"].append(count)
                        column6["Transaction_Type"].append(type)
                        column6["Transaction_Amount"].append(amount)
                        
top_insurance = pd.DataFrame(column6)

In [35]:
path7 = "C:/Phonepay_Transaction_insights/pulse/data/top/transaction/country/india/state/"

In [36]:
aggregated_map = os.listdir(path7)
column7= {"States":[],"Year":[],"Quarter":[],"Pin_code":[],"Transaction_Amount":[],"Transaction_Type":[],"Transaction_count":[]}

In [ ]:
for state in aggregated_map:
    curr_state = os.path.join(path7,state)
    current_state = os.listdir(curr_state)
    for year in current_state:
        curr_year = os.path.join(curr_state,year)
        current_year = os.listdir(curr_year)
        for file in current_year:
            file_path = os.path.join(curr_year,file)
            if file.endswith(".json"):
                with open(file_path,"r") as f:
                    data7 = json.load(f)
                    for i in data7['data']['pincodes']:
                        pin_code = i['entityName']
                        type = i['metric']["type"]
                        count = i['metric']["count"]
                        amount = i['metric']["amount"]
                        column7["States"].append(state)
                        column7["Year"].append(year)
                        quarter = int(os.path.splitext(file)[0])
                        column7["Quarter"].append(quarter)
                        column7["Pin_code"].append(pin_code)
                        column7["Transaction_count"].append(count)
                        column7["Transaction_Type"].append(type)
                        column7["Transaction_Amount"].append(amount)
                        
top_transaction = pd.DataFrame(column7)

In [57]:
path8 = "C:/Phonepay_Transaction_insights/pulse/data/top/user/country/india/state/"

In [58]:
aggregated_map = os.listdir(path8)
column8= {"States":[],"Year":[],"Quarter":[],"Pin_code":[],"RegisteredUsers":[]}

In [59]:
for state in aggregated_map:
    curr_state = os.path.join(path8,state)
    current_state = os.listdir(curr_state)
    for year in current_state:
        curr_year = os.path.join(curr_state,year)
        current_year = os.listdir(curr_year)
        for file in current_year:
            file_path = os.path.join(curr_year,file)
            if file.endswith(".json"):
                with open(file_path,"r") as f:
                    data8 = json.load(f)
                    for i in data8["data"]['pincodes']:
                        pin_code = i['name']
                        amount = i['registeredUsers']
                        column8["States"].append(state)
                        column8["Year"].append(year)
                        quarter = int(os.path.splitext(file)[0])
                        column8["Quarter"].append(quarter)
                        column8["Pin_code"].append(pin_code)
                        column8["RegisteredUsers"].append(amount)

In [60]:
Top_user = pd.DataFrame(column8)

In [61]:
Top_user

                         States  Year  Quarter Pin_code  RegisteredUsers
0     andaman-&-nicobar-islands  2018        1   744103             1608
1     andaman-&-nicobar-islands  2018        1   744101             1108
2     andaman-&-nicobar-islands  2018        1   744105             1075
3     andaman-&-nicobar-islands  2018        1   744102             1006
4     andaman-&-nicobar-islands  2018        1   744104              272
...                         ...   ...      ...      ...              ...
9995                west-bengal  2024        4   733134           169596
9996                west-bengal  2024        4   700059           169448
9997                west-bengal  2024        4   711302           146034
9998                west-bengal  2024        4   700150           142151
9999                west-bengal  2024        4   711106           142077

[10000 rows x 5 columns]